# rnd-containers Makefile — Layer-0 + Layer-1 build automation

# ── Persistent build config (optional) ──────────────────────
-include config.mk

# ── Configuration ────────────────────────────────────────────
HOLOSCAN_VER    ?= 3.11.0
REGISTRY        ?= docker.io
IMAGE_NAMESPACE ?= mikesrnd
IMAGE_SOURCE    ?= https://github.com/$(IMAGE_NAMESPACE)/rnd-containers
PROJECT         ?= ano
CUDA_VER        ?= 13.1
CUDA_PATCH      ?= 13.1.0
CUDA_FLAVOR     ?= base
CUDA_ARCHS      ?= 80;86;89;90;120
UBUNTU_VER      ?= 22

_HOLO_TAG   := holo$(HOLOSCAN_VER)

# Upstream NVIDIA CUDA image
BASE_IMAGE ?= nvcr.io/nvidia/cuda:$(CUDA_PATCH)-$(CUDA_FLAVOR)-ubuntu$(UBUNTU_VER).04

# Registry prefix: normalize trailing slash (works with or without user-supplied slash)
_REG := $(if $(REGISTRY),$(patsubst %/,%,$(REGISTRY))/,)

# Flavor suffix: empty for base, -devel or -runtime otherwise
_FLAVOR := $(if $(filter base,$(CUDA_FLAVOR)),,-$(CUDA_FLAVOR))

# Version tag component shared by local and push names: cuda12.6-ubu22[-devel]
_VTAG := cuda$(CUDA_VER)-ubu$(UBUNTU_VER)$(_FLAVOR)

# ── Local image tags (flat, for docker images | grep) ────────
BASE_TAG      ?= base-$(_VTAG)
HOLOHUB_TAG   ?= holohub-$(PROJECT)-$(_HOLO_TAG)
ANO_TOOLS_TAG ?= ano-tools-$(_HOLO_TAG)

# Export variables for the ano-dev sub-make
export HOLOSCAN_VER
export _HOLO_TAG
export HOLOHUB_TAG
export ANO_TOOLS_TAG
export CUDA_VER
export CUDA_ARCHS
export REGISTRY
export IMAGE_NAMESPACE
export IMAGE_SOURCE

# ──────────────────────────────────────────────────────────────
.PHONY: all base holohub-dpdk holohub-gpunetio holohub-rivermax \
        ano-tools ano-dev clean help configure show-config

all: base holohub-dpdk ## Build layer-0 + layer-1 dpdk (default)

# ── Build targets ────────────────────────────────────────────
base: ## Build layer-0 base image
	docker build \
		--build-arg BASE_IMAGE=$(BASE_IMAGE) \
		-t $(BASE_TAG) \
		-f containers/base/Dockerfile .

holohub-dpdk: base ## Build holohub with dpdk (default target)
	docker build \
		--build-arg BASE_TAG=$(BASE_TAG) \
		--build-arg HOLOSCAN_DEB_REMOTE_VERSION=$(HOLOSCAN_VER) \
		-t $(HOLOHUB_TAG)-dpdk \
		-f containers/ano/holohub/Dockerfile \
		containers/ano/holohub/

holohub-gpunetio: base ## Build holohub with gpunetio target
	docker build \
		--build-arg BASE_TAG=$(BASE_TAG) \
		--build-arg HOLOSCAN_DEB_REMOTE_VERSION=$(HOLOSCAN_VER) \
		--target gpunetio \
		-t $(HOLOHUB_TAG)-gpunetio \
		-f containers/ano/holohub/Dockerfile \
		containers/ano/holohub/

holohub-rivermax: base ## Build holohub with rivermax target
	docker build \
		--build-arg BASE_TAG=$(BASE_TAG) \
		--build-arg HOLOSCAN_DEB_REMOTE_VERSION=$(HOLOSCAN_VER) \
		--target rivermax \
		-t $(HOLOHUB_TAG)-rivermax \
		-f containers/ano/holohub/Dockerfile \
		containers/ano/holohub/

ano-tools: holohub-dpdk ## Build layer-2 SDK image
	docker build \
		--build-arg BASE_IMAGE=$(HOLOHUB_TAG)-dpdk \
		--build-arg HOLOSCAN_VER=$(HOLOSCAN_VER) \
		--build-arg CUDA_VER=$(CUDA_VER) \
		--build-arg CUDA_ARCHS="$(CUDA_ARCHS)" \
		-t $(ANO_TOOLS_TAG) \
		-f containers/ano-tools/Dockerfile \
		containers/ano-tools/

ano-dev: ano-tools ## Build ano-dev container
	$(MAKE) -C containers/ano-dev docker-build

# ── Utilities ────────────────────────────────────────────────
clean: ## Remove built images
	docker rmi -f $(BASE_TAG) \
		$(HOLOHUB_TAG)-dpdk \
		$(HOLOHUB_TAG)-gpunetio \
		$(HOLOHUB_TAG)-rivermax \
		$(ANO_TOOLS_TAG) 2>/dev/null || true
	$(MAKE) -C containers/ano-dev docker-clean 2>/dev/null || true

configure: ## Persist build settings to config.mk
	@echo "# Generated by: make configure" > config.mk
	@echo "HOLOSCAN_VER    := $(HOLOSCAN_VER)"    >> config.mk
	@echo "REGISTRY        := $(REGISTRY)"        >> config.mk
	@echo "IMAGE_NAMESPACE := $(IMAGE_NAMESPACE)" >> config.mk
	@echo "IMAGE_SOURCE    := $(IMAGE_SOURCE)"    >> config.mk
	@echo "CUDA_VER        := $(CUDA_VER)"        >> config.mk
	@echo "CUDA_ARCHS      := $(CUDA_ARCHS)"      >> config.mk
	@echo "Saved config.mk"

show-config: ## Print effective build settings
	@echo "Effective build configuration:"
	@echo "  HOLOSCAN_VER    = $(HOLOSCAN_VER)"
	@echo "  _HOLO_TAG       = $(_HOLO_TAG)"
	@echo "  REGISTRY        = $(REGISTRY)"
	@echo "  IMAGE_NAMESPACE = $(IMAGE_NAMESPACE)"
	@echo "  IMAGE_SOURCE    = $(IMAGE_SOURCE)"
	@echo "  HOLOHUB_TAG     = $(HOLOHUB_TAG)"
	@echo "  ANO_TOOLS_TAG   = $(ANO_TOOLS_TAG)"
	@echo "  BASE_TAG        = $(BASE_TAG)"
	@echo "  CUDA_ARCHS      = $(CUDA_ARCHS)"

help: ## Show this help
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'
